language: java
dist: trusty

addons:
  sonarcloud:
    organization: "sibadoge1-github" # the key of the org you chose at step #3
    token:
      secure: "$SONAR_TOKEN" # encrypted value of your token

before_install:
- chmod a+x ./Scripts/MSBuild.sh

script:
#- ./Scripts/MSBuild.sh
- sonar-scanner
# other script steps might be done before running the actual analysis
# - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar